// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

import { ENVIRONMENT } from "./configuration/environment";

export default defineConfig({
  schema: "configuration/prisma/schema.prisma",
  migrations: {
    path: "configuration/prisma/migrations",
  },
  datasource: {
    url: ENVIRONMENT.SUPABASE_CONNECTION_STRING,
  },
});
